[workspace]
members = ["cargo-mcp", "mcp-repl"]
resolver = "3"

[workspace.dependencies]
futures = { version = "0.3" }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
rmcp = { version = "0.3" }
tokio = { version = "1" }
