target = "docs/design/technical-spec.md#crate-information-resource"

# Crate Information Resource
#
# The server MUST provide a resource at path `crate/{name}/info`.
# 
# The server MUST execute the `cargo info` command to retrieve crate information.
# 
# The server MUST parse and return the latest version of the crate.
# 
# The server MUST return all available versions of the crate.
# 
# The server MUST return all available features and their descriptions.
# 
# The server MUST return the crate's dependencies.
# 
# The server SHOULD cache crate information with a shorter TTL than documentation.

[[spec]]
level = "MUST"
quote = '''
The server MUST provide a resource at path `crate/{name}/info`.
'''

[[spec]]
level = "MUST"
quote = '''
The server MUST execute the `cargo info` command to retrieve crate information.
'''

[[spec]]
level = "MUST"
quote = '''
The server MUST parse and return the latest version of the crate.
'''

[[spec]]
level = "MUST"
quote = '''
The server MUST return all available versions of the crate.
'''

[[spec]]
level = "MUST"
quote = '''
The server MUST return all available features and their descriptions.
'''

[[spec]]
level = "MUST"
quote = '''
The server MUST return the crate's dependencies.
'''

[[spec]]
level = "SHOULD"
quote = '''
The server SHOULD cache crate information with a shorter TTL than documentation.
'''

